### ISSUE TITLE
Custom "setTimeout" not equivalent to built-in, breaking RoboScape (and possibly more)

### ISSUE THREAD

**Issue by gsteinLTU** [NetsBlox/services#148]
The custom `setTimeout` added for testing does not accept arguments beyond the first two. The built-in `setTimeout` accepts additional arguments which are passed through to the function.

For RoboScape, this causes a crash when the robot's button is pressed.
```
/netsblox/src/procedures/roboscape/robot.js:410
            if (robot.buttonDownTime === pressed) {
                      ^

TypeError: Cannot read properties of undefined (reading 'buttonDownTime')
    at /netsblox/src/procedures/roboscape/robot.js:410:23
    at Timeout.cb [as _onTimeout] (/netsblox/src/timers.js:11:14)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
```

**Comment by gsteinLTU** [comment]
@brollb Can you please make the functions in timers.js variadic? There are probably other services expecting the normal behavior.
